### ISSUE TITLE
pictures

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/surface-nets#1]
![sphere](https://cloud.githubusercontent.com/assets/2310732/9207777/f78b7822-406f-11e5-9a14-98044c06ad46.jpg)

**Comment by naleksiev** [comment]
To fix the problem check line 110 "k = k << 1;" has to be at the end of the loop. Also check line 71.

**Comment by r03ert0** [comment]
argh! That was it! Thank you!

![sphere](https://cloud.githubusercontent.com/assets/2310732/14340850/f4720c22-fc8b-11e5-9d63-28790e0f5d21.jpg)

**Comment by r03ert0** [comment]
for the record, the error was in the translation of statement3 in 2 for loops that were like "i++,k++". The commands in statement3 are executed at the end of each loop, but when taking "k++" out of the "for" argument i had incorrectly placed it at the beginning and not at the end.
